default:
  image: ruby:2.5

rspec:
  script:
  - gem install sinatra
  - gem install json-schema
  - gem install rspec
  - rspec

rubocop:
  script:
  - gem install rubocop
  - rubocop

deploy:
  script:
  - gem install sinatra
  - gem install json-schema
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-ruby-test-staging --api-key=$HEROKU_STAGING_API_KEY
