default:
  image: ruby:2.5

stage: rspec
  script: 
  - bundle exec rspec

stage: rubocop
  script: 
  - bundle exec rubocop

stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-ruby-test-staging --api-key=$HEROKU_STAGING_API_KEY