default:
  image: ruby:2.5

rspec:
  script:
  - gem install rspec
  - bundle exec rspec

rubocop:
  script:
  - gem install rubocop
  - bundle exec rubocop

deploy:
  script:
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-ruby-test-staging --api-key=$HEROKU_STAGING_API_KEY
