default:
  image: ruby:2.5

rspec:
  script:
  - gem install sinatra
  - gem install json-schema
  - gem install rspec
  - rspec

rubocop:
  script:
  - gem install rubocop
  - rubocop

deploy:
  script:
  - gem install bundler
  - gem install sinatra
  - gem install json-schema
  - gem install dpl
  - bundle install
  - dpl --provider=heroku --app=zadeploy --api-key='82c1a418-84b0-41f0-8f13-f109be897745'
