default:
  image: ruby:2.7

rspec:
  script:
  - gem install sinatra
  - gem install json-schema
  - gem install rspec
  - rspec

rubocop:
  script:
  - gem install rubocop
  - rubocop

deploy:
  script:
  - gem install sinatra
  - gem install json-schema
  - gem install dpl
  - git add .
  - git push https://heroku:'82c1a418-84b0-41f0-8f13-f109be897745'@https://git.heroku.com/zadeploy.git master
  - dpl --provider=heroku git --app=zadeploy --api-key='82c1a418-84b0-41f0-8f13-f109be897745'
