default:
  image: ruby:2.7

rspec:
  script:
  - gem install sinatra
  - gem install json-schema
  - gem install rspec
  - rspec

rubocop:
  script:
  - gem install rubocop
  - rubocop

deploy:
  variables:
     HEROKU_API_KEY: "82c1a418-84b0-41f0-8f13-f109be897745"
     HEROKU_APP_NAME: "zadeploy"
  script:
  - git config --global user.email "itnewstudent@gmail.com"
  - git config --global user.name "Catherine"
  - git commit -m "initial commit"
  - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  
