default:
  image: ruby:2.5

rspec:
  script:
  - gem install sinatra
  - gem install json-schema
  - gem install rspec
  - rspec

rubocop:
  script:
  - gem install rubocop
  - rubocop

deploy:
  script:
  - gem install sinatra
  - gem install json-schema
  - gem install dpl
  - dpl --provider=heroku --app=zadeploy --api-key='933c8ec4-87c1-42ce-9391-983821811655'
